# Generated by Django 5.1.5 on 2025-03-16 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fullname',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
