# Generated by Django 5.1.7 on 2025-04-01 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_message_conversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='audio_file',
            field=models.FileField(default='default.mp3', upload_to='songs/'),
        ),
    ]
