# Generated by Django 5.1.7 on 2025-05-02 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_song_image_alter_playlist_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dateRegister',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='isRegister',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='monthRegister',
            field=models.IntegerField(default=2),
        ),
    ]
