# Generated by Django 5.1.7 on 2025-05-03 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_user_dateregister_user_isregister_user_monthregister'),
        ('api', '0012_alter_user_role'),
    ]

    operations = [
    ]
