# Generated by Django 5.1.7 on 2025-05-03 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_merge_20250503_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
    ]
